"""Type field added to model

Revision ID: 25cde4c67cae
Revises: 7ffad1f4d225
Create Date: 2024-08-11 17:50:45.332697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cde4c67cae'
down_revision = '7ffad1f4d225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=15), server_default='Regular', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
