"""options column added to product model

Revision ID: 41965e2f406a
Revises: 557c66fd5575
Create Date: 2024-08-18 11:26:49.646810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41965e2f406a'
down_revision = '557c66fd5575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.String(length=50), nullable=False))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('options')

    # ### end Alembic commands ###
