"""empty message

Revision ID: bdb70e09a042
Revises: 7af54d8127e5
Create Date: 2024-09-06 08:09:12.852978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb70e09a042'
down_revision = '7af54d8127e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=15), server_default=sa.text("'Regular'"), nullable=False))

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('options', sa.VARCHAR(length=50), nullable=True),
    sa.Column('price_regular', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('price_vip', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('price_lounge', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_product_category'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
